using System.Diagnostics;
using Xunit;

namespace Icod.Pty.Tests;

public sealed class UnixStartupTests {
	[Fact]
	public async Task Unix_cancelled_handshake_reaps_helper() {
		if (OperatingSystem.IsWindows()) return;
		await CheckHandshake(true, TimeSpan.FromSeconds(15));
	}
	[Fact]
	public async Task Unix_handshake_timeout_is_not_caller_cancellation() {
		if (OperatingSystem.IsWindows()) return;
		await CheckHandshake(false, TimeSpan.FromMilliseconds(300));
	}
	[Fact]
	public async Task Unix_caller_cancellation_before_deadline_preserves_caller_token() {
		if (OperatingSystem.IsWindows()) return;
		await CheckHandshake(true, TimeSpan.FromSeconds(3));
	}
	private static async Task CheckHandshake(bool cancelCaller, TimeSpan timeout) {
		if (OperatingSystem.IsWindows()) throw new PlatformNotSupportedException();
		string directory = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "icod-pty-start-" + Guid.NewGuid().ToString("N"))).FullName;
		string script = Path.Combine(directory, "host"), pidFile = Path.Combine(directory, "pid");
		// The directory is generated by this test, and contains no shell metacharacters.
		File.WriteAllText(script, "#!/bin/sh\nprintf '%s' \"$$\" > '" + pidFile + "'\nexec sleep 60\n");
		File.SetUnixFileMode(script, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
		using CancellationTokenSource cancellation = new();
		PtyStartInfo info = PtyTestSupport.Child(); info.DotNetHostPath = script; info.StartTimeout = timeout;
		Task<PtyProcess> pending = PtyProcess.StartAsync(info, cancellation.Token);
		int pid = 0;
		try {
			using CancellationTokenSource readyTimeout = new(TimeSpan.FromSeconds(5));
			while (!File.Exists(pidFile) || !int.TryParse(await File.ReadAllTextAsync(pidFile), out pid)) await Task.Delay(10, readyTimeout.Token);
			if (cancelCaller) {
				cancellation.Cancel();
				OperationCanceledException error = await Assert.ThrowsAnyAsync<OperationCanceledException>(() => pending.WaitAsync(TimeSpan.FromSeconds(2)));
				Assert.Equal(cancellation.Token, error.CancellationToken);
			} else await Assert.ThrowsAsync<TimeoutException>(() => pending);
			Assert.False(IsRunning(pid));
		} finally {
			if (pid != 0 && IsRunning(pid)) { using Process helper = Process.GetProcessById(pid); helper.Kill(); }
			try { using PtyProcess unexpected = await pending.WaitAsync(TimeSpan.FromSeconds(5)); } catch (Exception) { }
			Directory.Delete(directory, true);
		}
	}
	private static bool IsRunning(int pid) { try { using Process process = Process.GetProcessById(pid); return !process.HasExited; } catch (ArgumentException) { return false; } }
}
